tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002116",
        "surface": "#faf9f4",
        "on-tertiary-container": "#a89d8c",
        "surface-container-highest": "#e3e3de",
        "tertiary-fixed": "#eee1cd",
        "surface-variant": "#e3e3de",
        "on-surface": "#1b1c19",
        "surface-container": "#efeee9",
        "inverse-primary": "#a0d1bc",
        "primary": "#00261b",
        "outline": "#717974",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b9ccad",
        "background": "#faf9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e9e8e3",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#214f3f",
        "tertiary-fixed-dim": "#d1c5b2",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf9f4",
        "on-secondary-fixed-variant": "#3b4b33",
        "tertiary": "#262013",
        "on-primary": "#ffffff",
        "on-background": "#1b1c19",
        "secondary-container": "#d2e6c5",
        "inverse-on-surface": "#f2f1ec",
        "primary-fixed": "#bcedd7",
        "on-secondary-fixed": "#101f0b",
        "primary-container": "#0b3d2e",
        "on-secondary-container": "#56674e",
        "on-tertiary-fixed-variant": "#4e4637",
        "on-error": "#ffffff",
        "secondary": "#52634a",
        "outline-variant": "#c0c8c3",
        "inverse-surface": "#30312e",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#a0d1bc",
        "on-primary-container": "#79a894",
        "on-surface-variant": "#414944",
        "tertiary-container": "#3c3527",
        "surface-dim": "#dbdad5",
        "surface-container-low": "#f5f4ef",
        "error": "#ba1a1a",
        "secondary-fixed": "#d5e8c8",
        "surface-tint": "#396756",
        "on-tertiary-fixed": "#211b0f"
      },
      fontFamily: {
        "headline": ["Newsreader"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
}
